"""
Ward Name Mapping for Bengaluru Wards
Maps ward IDs to proper ward names for better user experience
"""

WARD_NAMES = {
    1: "Anekal",
    2: "Attibele",
    3: "Chandapura",
    4: "Sarjapur Road",
    5: "Mahadevapura",
    6: "Lingarajapuram",
    7: "C.V. Raman Nagar",
    8: "Shivaji Nagar",
    9: "Shanti Nagar",
    10: "Rajaji Nagar",
    11: "New Tippasandra",
    12: "Malleshwaram",
    13: "Hebbal",
    14: "Sahakar Nagar",
    15: "Byatarayanapura",
    16: "Yeshwanthpur",
    17: "Rajarajeshwari Nagar",
    18: "Vijayanagar",
    19: "Chamrajpet",
    20: "Chickpet",
    21: "Basavanagudi",
    22: "Padmanabhanagar",
    23: "Chamarajpet",
    24: "Bangalore Cantonment",
    25: "Brigade Road",
    26: "Victoria Layout",
    27: "Malleswaram",
    28: "Frazer Town",
    29: "Pulakeshinagar",
    30: "Jalahalli",
    31: "Rajagopalnagar",
    32: "Hennur",
    33: "Kalyan Nagar",
    34: "HBR Layout",
    35: "Horamavu",
    36: "Banaswadi",
    37: "Kammanahalli",
    38: "Vijayanagar East",
    39: "Hosakerehalli",
    40: "Maruthi Sevanagar",
    41: "Gandhi Nagar",
    42: "Subhash Nagar",
    43: "Okalipuram",
    44: "Seshadripuram",
    45: "Shivanagar",
    46: "Vasanth Nagar",
    47: "Cantonment",
    48: "Richmond Town",
    49: "Frazer Town",
    50: "Ulsoor",
    51: "Bharathi Nagar",
    52: "Sadashivanagar",
    53: "Malleswaram West",
    54: "Mattikere",
    55: "Yeshwanthpur",
    56: "HMT Layout",
    57: "Vidyaranyapura",
    58: "Dodda Bommasandra",
    59: "Kuvempu Nagar",
    60: "Kaval Bairasandra",
    61: "Pattegarhpalya",
    62: "Jalahalli Cross",
    63: "Dasarahalli",
    64: "Jalahalli West",
    65: "Akshaya Nagar",
    66: "Shankar Matt",
    67: "Gayatrinagar",
    68: "Doddabommasandra",
    69: "Agrahara Dasarahalli",
    70: "T. Dasarahalli",
    71: "Bagalagunte",
    72: "Nagavara",
    73: "Hennur Road",
    74: "HBR Layout",
    75: "Horamavu",
    76: "Ramamurthy Nagar",
    77: "Banaswadi",
    78: "Kammanahalli",
    79: "Kadugodi",
    80: "Hagadur",
    81: "Varthur",
    82: "Bellandur",
    83: "Sarjapur",
    84: "Kaikondrahalli",
    85: "Gunjur",
    86: "Whitefield",
    87: "Sarjapur Road",
    88: "Mahadevapura",
    89: "Lingarajapuram",
    90: "C.V. Raman Nagar",
    91: "Shivaji Nagar",
    92: "Shanti Nagar",
    93: "Rajaji Nagar",
    94: "New Tippasandra",
    95: "Malleshwaram",
    96: "Hebbal",
    97: "Sahakar Nagar",
    98: "Byatarayanapura",
    99: "Yeshwanthpur",
    100: "Rajarajeshwari Nagar",
    101: "Vijayanagar",
    102: "Chamrajpet",
    103: "Chickpet",
    104: "Basavanagudi",
    105: "Padmanabhanagar",
    106: "Chamarajpet",
    107: "Bangalore Cantonment",
    108: "Brigade Road",
    109: "Victoria Layout",
    110: "Malleswaram",
    111: "Frazer Town",
    112: "Pulakeshinagar",
    113: "Jalahalli",
    114: "Rajagopalnagar",
    115: "Hennur",
    116: "Kalyan Nagar",
    117: "HBR Layout",
    118: "Horamavu",
    119: "Banaswadi",
    120: "Kammanahalli",
    121: "Vijayanagar East",
    122: "Hosakerehalli",
    123: "Maruthi Sevanagar",
    124: "Gandhi Nagar",
    125: "Subhash Nagar",
    126: "Okalipuram",
    127: "Seshadripuram",
    128: "Shivanagar",
    129: "Vasanth Nagar",
    130: "Cantonment",
    131: "Richmond Town",
    132: "Frazer Town",
    133: "Ulsoor",
    134: "Bharathi Nagar",
    135: "Sadashivanagar",
    136: "Malleswaram West",
    137: "Mattikere",
    138: "Yeshwanthpur",
    139: "HMT Layout",
    140: "Vidyaranyapura",
    141: "Dodda Bommasandra",
    142: "Kuvempu Nagar",
    143: "Kaval Bairasandra",
    144: "Pattegarhpalya",
    145: "Jalahalli Cross",
    146: "Dasarahalli",
    147: "Jalahalli West",
    148: "Akshaya Nagar",
    149: "Shankar Matt",
    150: "Gayatrinagar",
    151: "Doddabommasandra",
    152: "Agrahara Dasarahalli",
    153: "T. Dasarahalli",
    154: "Bagalagunte",
    155: "Nagavara",
    156: "Hennur Road",
    157: "HBR Layout",
    158: "Horamavu",
    159: "Ramamurthy Nagar",
    160: "Banaswadi",
    161: "Kammanahalli",
    162: "Kadugodi",
    163: "Hagadur",
    164: "Varthur",
    165: "Bellandur",
    166: "Sarjapur",
    167: "Kaikondrahalli",
    168: "Gunjur",
    169: "Whitefield",
    170: "Sarjapur Road",
    171: "Mahadevapura",
    172: "Lingarajapuram",
    173: "C.V. Raman Nagar",
    174: "Shivaji Nagar",
    175: "Shanti Nagar",
    176: "Rajaji Nagar",
    177: "New Tippasandra",
    178: "Malleshwaram",
    179: "Hebbal",
    180: "Sahakar Nagar",
    181: "Byatarayanapura",
    182: "Yeshwanthpur",
    183: "Rajarajeshwari Nagar",
    184: "Vijayanagar",
    185: "Chamrajpet",
    186: "Chickpet",
    187: "Basavanagudi",
    188: "Padmanabhanagar",
    189: "Chamarajpet",
    190: "Bangalore Cantonment",
    191: "Brigade Road",
    192: "Victoria Layout",
    193: "Malleswaram",
    194: "Frazer Town",
    195: "Pulakeshinagar",
    196: "Jalahalli",
    197: "Rajagopalnagar",
    198: "Hennur",
    199: "Kalyan Nagar",
    200: "HBR Layout"
}


def get_ward_name(ward_id):
    """Get ward name by ID"""
    return WARD_NAMES.get(int(ward_id), f"Ward {ward_id}")


def get_ward_options():
    """Get list of ward options for dropdowns"""
    return [(str(wid), get_ward_name(wid)) for wid in sorted(WARD_NAMES.keys())]


def get_wards_list():
    """Get list of all wards with names"""
    return [{"id": wid, "name": name} for wid, name in WARD_NAMES.items()]